DROP DATABASE IF EXISTS recipe_db;
CREATE DATABASE recipe_db;
USE recipe_db;

CREATE TABLE recipes (
	id int NOT NULL AUTO_INCREMENT,
	recipe_name VARCHAR(200) NOT NULL,
	recipe VARCHAR(5000) NOT NULL,
	PRIMARY KEY (id)
);